jobs:
- job: Test
  timeoutInMinutes: 120
  pool:
    vmImage: ubuntu-latest

  steps:
  - task: Bash@3
    inputs:
      filePath: './build_aaos.sh'

  - script: echo "##vso[task.setvariable variable=imgDir;]$(pwd | sed 's/\/device\/brcm\/rpi4$//')/out/target/product/rpi4"
    displayName: 'get img dir'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(imgDir)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'